### ISSUE TITLE
Use the den API to create pubspecs

### ISSUE THREAD

**Issue by seaneagan** [google/stagehand#101]
Once the den API is published:

https://github.com/seaneagan/den/issues/5

it could be used by stagehand to create pubspecs with up-to-date version constraints.  Also, it would give stagehand the flexibility to ask interactive questions related to pubspec data, if stagehand wants to do that at some point in the future.

**Comment by seaneagan** [comment]
The den dart API is now available:

https://pub.dartlang.org/packages/den_api

**Comment by sethladd** [comment]
Patches welcome!
