### ISSUE TITLE
Singe versus double quotes in pubspec should be consistent with pub.dartlang

### ISSUE THREAD

**Issue by davenotik** [google/stagehand#162]
On pub.dartlang, it's a double quote, in stagehand it's a single quote. One or the other should be updated to be what's recommended or at least be consistent, because I find myself fixing a mix of single and double quotes when copying from pub.dartlang after I instantiated e.g. a shelfserver w/ stagehand.

**Comment by devoncarew** [comment]
Closing this out as the stagehand side has been addressed -
