### ISSUE TITLE
upgrade the polymer sample

### ISSUE THREAD

**Issue by devoncarew** [google/stagehand#170]
https://pub.dartlang.org/packages/paper_elements has reved to 0.6.0.

**Comment by kunaldeo** [comment]
I have modified the template little bit to work with the newest polymer and paper_elements packages .

https://github.com/google/stagehand/pull/196

**Comment by kunaldeo** [comment]
https://github.com/google/stagehand/pull/197 I have updated the polymer sample to work with the latest paper_elements and polymer packages.

**Comment by devoncarew** [comment]
fixed by #197
