### ISSUE TITLE
Semaphore Timeout when running pub global activate stagehand

### ISSUE THREAD

**Issue by jfphilbin** [google/stagehand#200]
I get the following error when trying to activate stagehand:
D:\dicom_web\api_test> pub global activate stagehand
Resolving dependencies...
+ args 0.12.2+3
+ collection 1.1.0
+ crypto 0.9.0
+ http 0.11.1+1
+ http_parser 0.0.2+5
+ path 1.3.2
+ source_span 1.0.3
+ stack_trace 1.1.2
+ stagehand 0.1.5+4
+ string_scanner 0.1.3
+ usage 0.0.6 (1.0.0 available)
Precompiling executables...
Loading source assets...
Failed to precompile stagehand:stagehand:
Unhandled exception:
Uncaught Error: SocketException: OS Error: The semaphore timeout period has expi
red.
, errno = 121, address = localhost, port = 63068
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:143)

D:\dicom_web\api_test>

**Comment by devoncarew** [comment]
This looks like a (hopefully transient) failure from pub, when it's trying to download stagehand and it's dependent packages. Does this error reproduce? Can you try pub global activate on any other tools?

If you pub cache is damaged, `pub cache repair` will try and fix it.

**Comment by sunglim** [comment]
I believe usage pacakge is damaged(it happen for me so frequently on my Window desktop)
If `pub cache repair` cannot fix it, try removing the  whole cache directory.

https://plus.google.com/113415344870093527255/posts/Tab8xQnqoFs

**Comment by jfphilbin** [comment]
I’ve repaired pub cache and deleted it,  but still get the same error:

Loading source assets...
Failed to precompile stagehand:stagehand:
Unhandled exception:
Uncaught Error: Load Error: SocketException: OS Error: The semaphore timeout period has expired.
, errno = 121, address = localhost, port = 61190
Stack Trace:
#0      _asyncLoadErrorCallback (dart:_builtin:335)
#1      _asyncLoadError (dart:_builtin:354)
#2      _httpGet.<anonymous closure> (dart:_builtin:45)
#3      _RootZone.runUnary (dart:async/zone.dart:1155)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:515)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:570)
#6      _Future._completeError (dart:async/future_impl.dart:366)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:421)
#8      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#9      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

**Comment by jfphilbin** [comment]
I am able to activate other packages (see below http, charcode, route), but still not stagehand.

D:\dicom_web\library>pub global activate http
Resolving dependencies...
+ collection 1.1.0
+ crypto 0.9.0
+ http 0.11.1+1
+ http_parser 0.0.2+5
+ path 1.3.2
+ source_span 1.0.3
+ stack_trace 1.1.3
+ string_scanner 0.1.3
Precompiling executables...
Loading source assets...
Activated http 0.11.1+1.

D:\dicom_web\library>pub global activate charcode
Resolving dependencies...
+ charcode 1.1.0
Precompiling executables...
Loading source assets...
Activated charcode 1.1.0.

D:\dicom_web\library>pub global activate shelf
Resolving dependencies...
+ collection 1.1.0
+ crypto 0.9.0
+ http_parser 0.0.2+5
+ path 1.3.2
+ shelf 0.5.7
+ source_span 1.0.3
+ stack_trace 1.1.3
+ string_scanner 0.1.3
Downloading shelf 0.5.7...
Precompiling executables...
Loading source assets...
Activated shelf 0.5.7.

D:\dicom_web\library>

**Comment by devoncarew** [comment]
I'm checking to see if either stagehand (or perhaps usage) is damaged. Those packages you activated above are libraries, not applications (i.e., they don't have executables defined in their pubspecs). Can you try activating a package with an executable, like `tuneup` or `grinder`.

**Comment by devoncarew** [comment]
(@jfphilbin)

**Comment by jfphilbin** [comment]
I tried activating both tuneup and grinder and both failed with the same error as stagehand, i.e. semaphore timeout.

I should mention that I am running version 1.9.0-dev.8.0.

**Comment by devoncarew** [comment]
OK, well that's good news at least; it's not specifically a stagehand issue. Can you file a bug at dartbug.com/new, with the stacktrace, and the info that this fails with many (all?) packages with executables?

**Comment by jfphilbin** [comment]
Will do.  Thanks for your help.  Jim

**Comment by devoncarew** [comment]
Thanks!
