### ISSUE TITLE
Create generator for Polymer element

### ISSUE THREAD

**Issue by luisvt** [google/stagehand#201]
Let's say that we want to generate a new polymer component. In that case we need to create two files:

* component.html
* component.dart

so that, this generator should create them for us, without generating pubspec.yaml and other files.

**Comment by sethladd** [comment]
I think that polymer.dart already has one of these.

cc @jakemac53

**Comment by jakemac53** [comment]
Yes, there is one and it lives here https://github.com/dart-lang/polymer-dart/blob/master/bin/new_element.dart. See also https://github.com/dart-lang/polymer-dart/blob/master/bin/new_entry.dart for creating a new entry point.

**Comment by luisvt** [comment]
it would be great have those generator in stagehand. In that way we could use them with Dart editor

**Comment by donny-dont** [comment]
:+1: to this. Also a way to add your own element generators would be great.

**Comment by sethladd** [comment]
We're going to defer to the generators in polymer.dart for now.

In the meantime, we're discussing a way to integrate third-party generators into stagehand. I'm guessing we'll converge. However, stagehand itself won't offer a polymer generator.
