### ISSUE TITLE
create a simple CLI sample

### ISSUE THREAD

**Issue by devoncarew** [google/stagehand#209]
This would be a counterpoint to the current CLI sample, and would not replace it.

Depends on #167

**Comment by sethladd** [comment]
Sounds like super simple is:

```
bin/main.dart
pubspec.yaml
```

**Comment by sethladd** [comment]
Actually, we need to add LICENSE and ensure main.dart has the license boilerplate at the top.

**Comment by sethladd** [comment]
Should we ship a version of stagehand that includes this?
