### ISSUE TITLE
Prompt for analytics opt-in on `stagehand <generator>` instead of `stagehand --help`

### ISSUE THREAD

**Issue by seaneagan** [google/stagehand#214]
(splitting this out of #147)

It would be much better UX to prompt on the first invocation of stagehand <generator> than on `stagehand` or `stagehand --help`, since the user may never even run the latter while using the tool, and doesn't usually expect to be prompted when requesting help.

Generally you only want to prompt when the script is being run interactively, which is determined by [stdioType](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:io#id_stdioType).  However, [this bug](http://dartbug.com/21821) prevents pub scripts from using that.

@sethladd suggested to require --machine for tool driven usage, which would allow us to infer interactive usage from its absence.  Also, --machine could return some output indicating that an opt-in is not yet provided, which a tool could use to do it's own prompt (using some text that was provided in the output).  Then if the user agrees, the tool could call stagehand with a hidden flag to register the opt-in e.g. `stagehand --opt-in`.  Or if that's not secure, maybe the output would contain some token that could be passed back in e.g. `stagehand --opt-in-key=sd89f#$SEF2`.

@devoncarew do you know if all the tools stagehand has been integrated into already use --machine?

(I ran into this when working on #211, since unscripted doesn't support running arbitrary code for --help, since that's not a common thing to do.)

**Comment by devoncarew** [comment]
They only pass `--machine` in when querying for the available templates. When generating a template, they just use `stagehand foo-bar`. We could change the convention and patch the clients, but it would take a while for that change to work its way to end users. IntelliJ in particular has a long release cycle.

Any way to infer non-interactive mode, using OS specific code?
