### ISSUE TITLE
Consider using resource_loader instead of including resources in .dart code

### ISSUE THREAD

**Issue by sethladd** [google/stagehand#227]
This might help:

https://github.com/dart-lang/dartdoc/blob/master/lib/resource_loader.dart

It can identify resources in a variety of scenarios.

**Comment by sethladd** [comment]
If this library is useful (as it is in dartdoc), I'd be happy to extract it out to a separate package.

**Comment by devoncarew** [comment]
I think this functionality would be generally useful. Like with a few other packages, it's good to have this logic in one places, instead of ad-hoc logic spread throughout apps that need it.

**Comment by sethladd** [comment]
Let me know if/when you want to try it out. Can packagify it.
