### ISSUE TITLE
create a simple CLI template as a separate repo

### ISSUE THREAD

**Issue by devoncarew** [google/stagehand#244]
Create a simple CLI template as a separate repo + pub package (related to #209 and #243).

@sethladd, could you create the repo?

**Comment by sethladd** [comment]
Do we have a naming scheme for the repos?

If not, what about:

dart-template-simple-cli

Start with 'dart-template' ?

**Comment by devoncarew** [comment]
We have a naming scheme for the templates themselves (https://github.com/google/stagehand). So the CLI one would be `console-simple`.

Having a common prefix for the stagehand default templates would be good - it'd help to namespace them within a github org. So, `dart-template-console-simple`, `stagehand-template-console-simple`, `stagehand-console-simple`?

**Comment by sethladd** [comment]
yeah, probably want to prefix with stagehand- because these templates will use specific stagehand capabilities.

so, we'll have `stagehand-template-console-simple` etc

**Comment by donny-dont** [comment]
One thing you might want to think about is having an organization with templates in it. Hubot does something like that https://github.com/github/hubot-scripts so there's a bit more visibility of whats available.

**Comment by sethladd** [comment]
Created here: https://github.com/google/stagehand-console-simple

(Google doesn't encourage lots of orgs on Github)
