### ISSUE TITLE
Update web templates to have <script> tags in <head>

### ISSUE THREAD

**Issue by kwalrath** [google/stagehand#260]
...and to otherwise match dartlang.org and DartPad samples.

For details, see the corresponding dartlang.org bug: [1428](https://github.com/dart-lang/www.dartlang.org/issues/1428)

**Comment by kwalrath** [comment]
Unless someone else is updating these templates, I plan to update them tomorrow. OK?

**Comment by devoncarew** [comment]
sgtm!

**Comment by kwalrath** [comment]
By "tomorrow" two days ago, I meant "today". OK, starting now...
