### ISSUE TITLE
remove reference to drone

### ISSUE THREAD

**Issue by sethladd** [google/stagehand#268]
There's a tool/drone.sh

**Comment by sethladd** [comment]
https://codereview.appspot.com/261330043

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by kevmoo** [comment]
Closed by https://codereview.appspot.com/261330043, right?

**Comment by kevmoo** [comment]
Er, 5ae702a60049934b92938c7e1736f78d787718fe
