### ISSUE TITLE
update the polymer dep from 1.0.0-rc.1

### ISSUE THREAD

**Issue by devoncarew** [google/stagehand#269]
We should push a new version of the template when `1.0.0` is stable, so people's app don't have `1.0.0-rc.1` (or `1.0.0-rc.2`) in them.

@jakemac53

**Comment by devoncarew** [comment]
(new template here: https://github.com/google/stagehand/pull/266)

**Comment by terrywarwar** [comment]
Polymer versions were created with:
polymer_elements: ^1.0.0-rc.2
polymer: ^1.0.0-rc.1

They should be: 
polymer_elements: ^1.0.0-rc.1
polymer: ^1.0.0-rc.2

**Comment by jakemac53** [comment]
doh! I can work on a pull request

**Comment by devoncarew** [comment]
@jakemac53, should we rev to the latest (`-rc5`?)? Or does the current sample work against that one?

**Comment by jakemac53** [comment]
current sample should still work

**Comment by jakemac53** [comment]
In the `rc` phase I am releasing versions pretty regularly (at least once a week) so I don't think its work tracking those for stagehand as long as it works in the latest

**Comment by devoncarew** [comment]
:+1: makes sense to me
