### ISSUE TITLE
'Polymer Web Application' doesn't work

### ISSUE THREAD

**Issue by alexander-doroshko** [google/stagehand#293]
Originally [reported by WebStorm user](https://devnet.jetbrains.com/message/5565539#5565539).

I checked with Dart SDK 1.13, corresponding Dartium and Chrome 47.0.2526.73, it doesn't work for me either. Here's what I see both in Dartium and in Chrome:
![image](https://cloud.githubusercontent.com/assets/4499789/11591035/c181c61a-9aa5-11e5-895e-baffb8b56ef1.png)

**Comment by devoncarew** [comment]
@kevmoo, a regression from the templating change?

**Comment by devoncarew** [comment]
re-published

**Comment by alexander-doroshko** [comment]
Works for me now. Thank you for this super fast turnaround!

**Comment by kevmoo** [comment]
![bitmoji-1088394539](https://cloud.githubusercontent.com/assets/17034/11599712/3861cec0-9a7d-11e5-8840-ae7cc9532b82.png)

**Comment by alexander-doroshko** [comment]
Sorry for bothering you. The user is asking related question that I do not completely understand and do not know an answer (see [here](https://devnet.jetbrains.com/message/5565589#5565589) for context):
```
But what do I need to add to get it work in Edge please? 
 
<script src="packages/web_components/webcomponents.min.js"></script>
<script src="packages/web_components/dart_support.js"></script>
 
doesn't work for me (and it doesn't work in Dartium)
```
