### ISSUE TITLE
Please remove "library" tags from Dart code.

### ISSUE THREAD

**Issue by Sfshaza** [google/stagehand#297]
We no longer recommend that developers write an explicit library tag - a default tag is generated for you using the path/filename and is guaranteed to be unique.

**Comment by kwalrath** [comment]
We should hold off on this change until we figure out what the story is for generating library-level API docs.

**Comment by devoncarew** [comment]
@keertip

**Comment by kwalrath** [comment]
The bug for the dartdoc update is here: https://github.com/dart-lang/dartdoc/issues/1082. We might need other fixes, as well...

**Comment by kwalrath** [comment]
We've changed our mind on holding off, btw...

**Comment by devoncarew** [comment]
PR's welcome :)

**Comment by Kleak** [comment]
for this one the remove has to be done on the source of stagehand or also on the template source ?

**Comment by kwalrath** [comment]
It'll require changing the template source and doing a regen. We've already applied this change to the web-angular template, btw. [web-angular/lib/app_component.dart](https://github.com/google/stagehand/blob/master/templates/web-angular/lib/app_component.dart), for example, has no `library` directive.

**Comment by Kleak** [comment]
not sure this is correct : https://github.com/Kleak/stagehand/tree/remove_library ?
if yes i can PR

**Comment by kwalrath** [comment]
Go ahead and PR so I can see the diffs. Thanks!

**Comment by kwalrath** [comment]
Only one library directive remains, and it's warranted due to the way library docs get generated. (We could change the example to make it have another directive there, but for now...)
