### ISSUE TITLE
No template/scaffolding for an Angular2 TypeScript project 

### ISSUE THREAD

**Issue by st-clair-clarke** [google/stagehand#310]
Hi,
I am requesting if there could be a template to generate an Angular2 TypeScript project in WebStorm.

Cheers

**Comment by kwalrath** [comment]
I'm not sure where a TS template should go, but it wouldn't be here. (You wouldn't see it in WebStorm unless you were creating a Dart project.) Perhaps try filing a bug with jetbrains.com? Or giving feedback on the angular.io site?
