### ISSUE TITLE
Does it make sense to add .analysis_options to all templates?

### ISSUE THREAD

**Issue by filiph** [google/stagehand#329]
We can do it in two ways. Either going with the `dartanalyzer` defaults by default but making it easy to customize. So the file would look something like this:

```
# analyzer:
#  strong-mode: true
#  excludes:
#    - path/to/excluded/files/**
# linter:
#   rules:
#     # see catalogue here: http://dart-lang.github.io/linter/lints/
#     - hash_and_equals
```

Or we can 'opinionate' and uncomment the first two lines. I'm leaning towards the second option.

**Comment by devoncarew** [comment]
+1 to the second option -

**Comment by devoncarew** [comment]
Although, we'd want to make sure all the templates analyze cleanly on strong mode first :)

**Comment by devoncarew** [comment]
@kwalrath, what do you think about this (going strong by default)?

**Comment by kwalrath** [comment]
I like it. @kevmoo, any opinion?

**Comment by kevmoo** [comment]
Uh...um...this makes me a bit nervous.

Once we lock down our external messaging/planning around strong mode & DDC, I'd vote no.

While it's cool for power users to play with, I'm worried that we'll throw a bunch of warnings and errors at folks that will be really confusing in the short term – without a documented payoff in the medium term.

**Comment by filiph** [comment]
If we injected into existing project, I'd agree.

But stagehand is for building new projects, and — as far as I can tell — when you start with strong mode on, it's very smooth sailing (you deal with issues when you actually write the code as opposed to many months later).

**Comment by kevmoo** [comment]
> when you start with strong mode on, it's very smooth sailing (you deal with issues when you actually write the code as opposed to many months later).

I agree except for one huge exception: generic methods.

The comment-based generic method syntax is an enormous pain. And it gets hit a lot – at least in my experience.

**Comment by filiph** [comment]
Good point.

So, option one (everything commented out by default) then? I still think it should be much easier to turn strong mode and linter on.

**Comment by kevmoo** [comment]
Sure. As long as we're *heavy* on the instructions. Link to the strong mode docs, etc.
