### ISSUE TITLE
Create app_component.css

### ISSUE THREAD

**Issue by filiph** [google/stagehand#332]
The angular2 template currently doesn't have app_component.css (and therefore no styleUrls record). I think most people will want to have styling in their components sooner or later (probably sooner).

It's just one additional line in app_component.dart and it's our chance to educate-by-example about:

* how one does styling in AngularDart
* `:host`

If there's a consensus, I'll prepare the PR.

**Comment by chalin** [comment]
Adding a style file for the component is a good idea, but I'm not sure that putting `:host` in it makes the most sense. Why not use `body` instead?

cc @kwalrath

**Comment by filiph** [comment]
I'm not knowledgeable enough about CSS (in or outside of Angular 2) to really have a strong opinion on this.

Wouldn't a `body` selector leak out of the component? Would it even apply (the component doesn't contain a `body` element)? I'm not able to check at the moment. In general, we want to use something that people can just copy-paste to other components and things will just work.

I see a lot of `:host` in component CSS. Actually, looking at Google's AngularDart components (unreleased as of today), it seems to be the _only_ way used to style the whole component.

**Comment by chalin** [comment]
Right, I'm not even sure what the behavior would be if `body` was styled. It isn't _supposed_ to leak out, but in that case, it would have no effect.

The generated sample template uses an `<h1>` element. Perhaps that could be styled.

I don't feel strongly about it either, if you think making use of `:host` without explanation would be ok.

@kwalrath - thoughts?

**Comment by kwalrath** [comment]
idk. Maybe @ferhatb or @matanlurey can recommend something?

**Comment by chalin** [comment]
Actually, I'd say let's merge as is ... and if we get too many questions about `:host`, we can adjust either the CSS or add some prose somewhere.

**Comment by kwalrath** [comment]
SGTM. Merging...

**Comment by filiph** [comment]
Thanks Kathy!
