### ISSUE TITLE
remove the app engine sample?

### ISSUE THREAD

**Issue by devoncarew** [google/stagehand#338]
`App Engine Application`; I don't think it's heavily used...

![screen shot 2016-09-15 at 4 55 50 pm](https://cloud.githubusercontent.com/assets/1269969/18593088/ad27b0e6-7bee-11e6-8ba8-b0bd5bdc3665.png)

@kevmoo @kwalrath

**Comment by kevmoo** [comment]
And it's not well documented. Likely a bigger pain to keep than to maintain.

**Comment by devoncarew** [comment]
Cool, I'll open a PR to remove it.
