### ISSUE TITLE
add bazel-* directories to the default exclude pattern?

### ISSUE THREAD

**Issue by devoncarew** [google/stagehand#344]
@kevmoo @kwalrath, thoughts on adding the default `bazel-*` directories to the .analysis_options exclude pattern?

**Comment by kevmoo** [comment]
Hrm...let's work on it at the `bazelify` level. Keep this tracking issue around, though 😄

**Comment by natebosch** [comment]
Inside the bazel package we'll probably only end up printing a message if you already have an analysis_options which is missing this exclude. We can safely create a default if there is no analysis options yet, but trying to edit an existing options file is risky.

IMO it would be sensible to include bazel-* in exclude if stagehand is generating default options already.

**Comment by natebosch** [comment]
After some more discussion we might want to hold off until bazel is the officially recommended development path. While it's still so experimental it doesn't make sense to cloud up most people's analysis options.

**Comment by devoncarew** [comment]
closing for now -
