### ISSUE TITLE
Angular2: add core directives and common pipes to angular2 pubspec options

### ISSUE THREAD

**Issue by xxgreg** [google/stagehand#349]
Consider adding the following entries to the angular2 pubspec.yaml template.

This will make it easier for people to get started immediately.

```
- angular2:
    platform_directives: 'package:angular2/src/common/directives.dart#CORE_DIRECTIVES'
    platform_pipes: 'package:angular2/common.dart#COMMON_PIPES'
```

**Comment by kwalrath** [comment]
@kevmoo & @matanlurey, I apparently didn't object to removing these lines in #335, but it sounds like having these is helpful.

**Comment by xxgreg** [comment]
New to Angular, so I'm not sure what the common practise is. Most code examples I've seen assume these are included.

**Comment by kevmoo** [comment]
Sounds like we should add 'em back.

**Comment by kwalrath** [comment]
OK, I'll prep a PR.

**Comment by kwalrath** [comment]
PR #350 adds the original code back to the pubspec. Note that the PR's code is slightly different from what @xxgreg suggested. Instead of CORE_DIRECTIVES, it uses COMMON_DIRECTIVES, and instead of `package:angular2/src/common/directives.dart`, it uses `package:angular2/common.dart`.
