### ISSUE TITLE
pubspec: browser as regular dependency?

### ISSUE THREAD

**Issue by chalin** [google/stagehand#351]
@devoncarew: I can understand why `dart_to_js_script_rewriter` was changed to be a dev dependency, but shouldn't `browser` be kept as a (regular) dependency? Cf. https://github.com/google/stagehand/commit/2c5621b96b56bff712b4c6dca5ec200052924c4e#diff-cd40c46ab3c9c543264af62536ab7b7fR10

I'm about to propagate pubspec changes to the Angular Dart samples, but wanted to double check with you first.

cc @kwalrath

**Comment by devoncarew** [comment]
The `dart_to_js_script_rewriter` tool removes references to the `browser` artifacts from the html file during a build, so the browser package is only needed at development time, not deployment time.

I'm not sure it's critical to move browser to a dev_dependency - perhaps nice hygiene.

**Comment by chalin** [comment]
Ah, I see. So does that mean that use of `dart_to_js_script_rewriter` and running Dart natively in Dartium are mutually exclusive? (I though that at some point they were not.)

**Comment by devoncarew** [comment]
Yes, I think it does. It rewrite html to remove references to the `browser` bootstrap script, and rewrites `dart/application` script references to target the compiled JS.

**Comment by chalin** [comment]
Ok, thanks!
