### ISSUE TITLE
Update web-angular template strings

### ISSUE THREAD

**Issue by kwalrath** [google/stagehand#352]
web-angular currently shows up in IDEs as `Angular 2 Web Application` with the description `A web app built using Angular 2.`

We should probably modify [lib/generators/web_angular.dart](https://github.com/google/stagehand/blob/master/lib/generators/web_angular.dart) to update/improve at least the title to use AngularDart, not Angular 2.

**Comment by devoncarew** [comment]
fixed in https://github.com/google/stagehand/pull/353?

**Comment by kwalrath** [comment]
Yep.
