### ISSUE TITLE
web-angular app should have keyboard alternative

### ISSUE THREAD

**Issue by kwalrath** [google/stagehand#358]
When you type in your name and press Return (on Mac, at least) nothing happens. You have to click the button or tab over to it and press Return/space.

**Comment by filiph** [comment]
I just implemented this and it adds code that no longer seems like 'hello world'. It could be a great step in a tutorial, though. It introduces things like Dart's abstracted (non-browser-specific) KeyboardEvent.

FWIW, I don't think this is a bug. With some inputs you definitely don't want to have Enter act as something that opens modal dialogs. But I do agree it would be a logical next feature to add in this particular case.

**Comment by kwalrath** [comment]
This issue was moved to dart-lang/site-webdev#278

**Comment by chalin** [comment]
Fixed by #426
