### ISSUE TITLE
Add <base href="/"> to index.html in an Angular project

### ISSUE THREAD

**Issue by kulshekhar** [google/stagehand#360]
Currently this needs to be added manually whenever routing is needed and it would be quite convenient if this were present in the template generated by Stagehand, at least in the `web-angular` template if not also in the `web-angular-quickstart` template

**Comment by kwalrath** [comment]
Thanks for filing this issue, @kulshekhar.

@chalin @filiph @matanlurey: thoughts?

**Comment by matanlurey** [comment]
Sgtm

**Comment by chalin** [comment]
This has been addressed by #365 and can be closed.
