### ISSUE TITLE
Angular template: in analysis options, enable strong-mode

### ISSUE THREAD

**Issue by chalin** [google/stagehand#368]
Cf. https://github.com/google/stagehand/blob/master/templates/web-angular/analysis_options.yaml#L6

@matanlurey @filiph @devoncarew @kevmoo - is there any reason _not_ to do this?

cc @kwalrath

**Comment by devoncarew** [comment]
@kevmoo had some concerns (a while ago) about strong mode and some unresolvable errors from streams? Those may have since become non-issues.

**Comment by kevmoo** [comment]
`LineSplitter` from `dart:convert` still has issues.

But nothing else that I'm aware of. The angular apps I play with always have strong mode on.

**Comment by chalin** [comment]
@kevmoo  - so, thumbs up to turn strong mode on in the ng templates?

**Comment by kevmoo** [comment]
Yup!

**Comment by chalin** [comment]
Great! Any of the lint options that we can turn on while we're there?

**Comment by kevmoo** [comment]
Let's hold off the lints for now. We really haven't decided what's going to be our official guidance here...

**Comment by filiph** [comment]
SGTM on strong mode.

I'd like to propose to turn on these error-lints (they are life-savers and a unique selling point of Dart):

* cancel_subscriptions
* close_sinks
* hash_and_equals
* invariant_booleans
* iterable_contains_unrelated_type
* list_remove_unrelated_type
* test_types_in_equals
* unrelated_type_equality_checks
* valid_regexps

**Comment by devoncarew** [comment]
/cc @pq on recommended lints

fyi, invariant_booleans currently comes with a fair performance penalty in terms of analysis time (https://github.com/dart-lang/linter/issues/434)

**Comment by pq** [comment]
👍  To @devoncarew's point, I'd agree that we want to wait on a fix to dart-lang/linter#434, before flipping the bit for `invariant_booleans`.  Otherwise, good with the sentiment.

@filiph : when we do explore something like this, some explanatory text would be good, probably with a link to the linter [docs](https://dart-lang.github.io/linter/)?

**Comment by alexeieleusis** [comment]
The performance problem with invariant_booleans has a PR open, so it should be fixed pretty soon.
