### ISSUE TITLE
stagehand web-simple  produces launcher with type: CLI

### ISSUE THREAD

**Issue by leemke** [google/stagehand#371]
I ran "stagehand web-simple" in a new directory (empty)
then ran "pub get".  It seemed to have built a reasonable directory structure.
(Since I am new to this - I cannot be certain).

However when I went to launch "main.dart" in the "web" subdirectory,
I received an error which said "cannot find "dart:html" (i.e. the one import in main.html)

I looked into the "main.yaml" dataset in the launcher directory. It contained
an attribute "type: cli". 

From another "simple console" type project I take this to mean a "command line interface".

According to documentation on the web  this is a normal failure because you cannot
access the "dart:html" package from a command line interface. 

So this seems to be an error!  Now the question is what should the value of the
"type" attribute be?  And will the "simple-web" option really work, or has something 
changed.   

By-the-way: all software was just installed in the past 5 days. So I assume it is 
up-to-date.

**Comment by chalin** [comment]
Hi @leemke, I'd suggest you try following the steps in either:

- (1) [Get Started with AngularDart](https://webdev.dartlang.org/guides/get-started), or
- (2) [Setup for Development](https://webdev.dartlang.org/angular/guide/setup) with AngularDart.

(2) actually covers using stagehand from the command line.

cc @kwalrath

**Comment by kwalrath** [comment]
Because it's a web app, you can't run it from the command line. Instead, run this:

```
pub serve
```

Then you'll be able to run the app in a browser.

Can you tell me your path to trying out stagehand? (I want to make sure we prominently link to docs that would've helped you get started in an easier way.)
