### ISSUE TITLE
change web-angular* templates to allow - in the project name

### ISSUE THREAD

**Issue by kwalrath** [google/stagehand#374]
See https://github.com/google/stagehand/pull/365#issuecomment-285537758.

We'll need corresponding changes to the site-webdev Angular examples.

**Comment by filiph** [comment]
When's the next release of stagehand? People are bumping into this issue (https://github.com/google/stagehand/issues/379).

**Comment by kwalrath** [comment]
I'll release it right now.

**Comment by kwalrath** [comment]
And it's out: 1.0.24

**Comment by filiph** [comment]
Thank you Kathy!
