### ISSUE TITLE
Remove the doc/api/ ignore in the .gitignores

### ISSUE THREAD

**Issue by kevmoo** [google/stagehand#375]
I think it's pretty rare for folks to run this tool themselves.

If they do, it's easy to add.

Optimize for the 95% case.

**Comment by chalin** [comment]
SGTM

**Comment by devoncarew** [comment]
FWIW, I'd be in favor of keeping this line in the .gitignores; we do ship dartdoc as part of the SDK, and w/o this line you could inadvertently commit a very large set of files to your repo.

**Comment by kevmoo** [comment]
Does dartdoc default to this directory?

**Comment by kevmoo** [comment]
...yes it does. K. Fair. Closing.
