### ISSUE TITLE
Suggestion: web-stagexl

### ISSUE THREAD

**Issue by Tomucha** [google/stagehand#377]
StageXL seems to be one of the strongest "weapons" in Dart ecosystem.

Would you be interested in "web-stagexl" template?

If you don't mind - I ask first and create pull request later ...

**Comment by filiph** [comment]
FWIW, I love that idea.

**Comment by kwalrath** [comment]
@kevmoo what do you think?

**Comment by kevmoo** [comment]
Sure!

**Comment by Tomucha** [comment]
Bernhard is on board (see StageXL Gitter), so if you don't mind, I'll take care of it.
https://gitter.im/bp74/StageXL

I'll prepare it, he will review it and then - pull request.
