### ISSUE TITLE
Say "AngularDart" instead of "Angular" in templates

### ISSUE THREAD

**Issue by kwalrath** [google/stagehand#387]
See https://github.com/dart-lang/site-webdev/issues/490.

**Comment by chalin** [comment]
Is this a request to rename the template to web-angulardart, or just to ensure that in the template files we use "AngularDart" rather than just "Angular".  If the latter, then I think that this is done.

**Comment by kwalrath** [comment]
I believe it's this:

>  Replace the name of the sample application template Angular Web Application with "AngularDart Web Application" and "Simple Angular Example" with "Simple AngularDart Example"

Which I'm in the process of doing.

**Comment by kwalrath** [comment]
The remaining AngularDart template now says "AngularDart":

![image](https://cloud.githubusercontent.com/assets/2164483/25925963/dea22d38-35a0-11e7-865f-4dcf31cfe479.png)
