### ISSUE TITLE
Improve the StageXL template description

### ISSUE THREAD

**Issue by kwalrath** [google/stagehand#402]
The StageXL template isn't getting many users. Let's see if improving the description helps.

Here's the current description:
* `web-stagexl        - A basic 2D canvas app with StageXL.` (command line)
* **Simple StageXL Application - a basic 2D canvas app with StageXL.** (IDE)

Although the new IDE description can't be much longer, we can subtract characters from the left side of the `-` to add to the right side. We don't need to mention "StageXL" on the right side. Possible words to use on the right side:
* WebGL
* game
* animation

Maybe we could have something like:
* **StageXL Web App - a starting point for WebGL-based animation and games.**

What do you think, @filiph, @Tomucha, and @bp74?

The other template descriptions, for reference:
* Console Application - a command-line application sample.
* Dart Package - a starting point for Dart libraries or applications.
* Shelf Web Server - a web server built using the shelf package.
* AngularDart Web App - a web app with material design components.
* Low-level HTML App - a bare-bones web app.

**Comment by Tomucha** [comment]
@kwalrath Thanks for keeping my baby alive!

WebGL evokes 3D, but StageXL is 2D only.

I vote for:
StageXL Web App - a starting point for 2D animation and games

**Comment by kwalrath** [comment]
Fixed in #403.
