### ISSUE TITLE
Release stagehand 1.1.2

### ISSUE THREAD

**Issue by kwalrath** [google/stagehand#406]
Before we release:

* [x] Prep PR for updating [Get Started](https://webdev.dartlang.org/guides/get-started) (see: https://github.com/dart-lang/site-webdev/pull/609).
   * [x] Create new Dartpad for step 1. 
* [x] Prep PR that updates stagehand version to 1.1.2: https://github.com/google/stagehand/pull/408.

Release:

* [x] Accept stagehand PR. Do the usual pub-lish dance.
* [x] Publish https://github.com/dart-lang/site-webdev/pull/609.

After we release:

* [x] Update all [docs that depend on stagehand](https://github.com/google/stagehand/wiki/Docs-that-depend-on-stagehand) (including Google I/O codelabs-to-be):
  * [x] Take new screenshots for everywhere that has references to New Project window.
     * https://github.com/dart-lang/site-webdev/pull/611, ...
  * [x] Update all text referring to Stagehand templates/descriptions. 
* [x] Update the list of [docs that depend on stagehand](https://github.com/google/stagehand/wiki/Docs-that-depend-on-stagehand). #390

**Comment by chalin** [comment]
The list looks complete.
