### ISSUE TITLE
Publish 1.1.3 once examples are updated

### ISSUE THREAD

**Issue by kwalrath** [google/stagehand#412]
AngularDart examples (in webdev & codelabs) should apply the web-angular template changes in [these diffs](https://github.com/google/stagehand/pull/409/files#diff-bdff46c00060bf16b8a0e446d2a2fad4).

When the webdev/codelab changes are ready to go, we should publish stagehand.

**Comment by chalin** [comment]
I'm working my way through the AngularDart examples: https://github.com/dart-lang/site-webdev/issues/624

**Comment by kwalrath** [comment]
Examples are updated, so I've published 1.1.3.
