### ISSUE TITLE
Update web-angular version or rely on ^?

### ISSUE THREAD

**Issue by kwalrath** [google/stagehand#419]
angular is now 3.1.0, and angular_components is 0.5.2. Should we update the pubspec versions (and risk looking out of date) or just rely on `^`?

See also https://github.com/dart-lang/angular_components/pull/97#discussion_r119688901.

/cc @filiph

**Comment by chalin** [comment]
I've generally preferred updating the pubspec since the version changes aren't that frequent.

**Comment by kwalrath** [comment]
There are just lots of downstream changes (e.g. text and examples in every codelab, text and examples in the docs, every step/branch of https://github.com/dart-lang/io_2017_components_codelab, ...).

**Comment by chalin** [comment]
I suppose that we can let `^` do its work.

**Comment by kevmoo** [comment]
It's tricky. If we start using features in 3.1.0 we *should* update the constraint.

...but it's hard to know when we do it without testing the older framework. 🤷‍♂️

**Comment by kwalrath** [comment]
Closing because we're not using 3.1.0 features.
