### ISSUE TITLE
analysis_options templates should not include 'close sinks' 

### ISSUE THREAD

**Issue by jonahwilliams** [google/stagehand#438]
The analysis_options templates (at least the web + angular ones) should probably not include the `close sinks` rule.  In the vast majority of cases, it is not necessary to close sinks, only single subscription streams or IO.  

For example, Angular applications use broadcast streams to dispatch events but closing a broadcast stream is almost a no-op.  This also makes Angular Dart look more verbose than it needs to be:

1.  add a field with a `StreamController`.
2.  add a getter with an `Output` annotation.
3.  implement `onDestroy`.
4.  add a `controller.close()` invocation in the `ngOnDestroy` method.

I've seen a lot of confusion about this rule internally as well.  People have assumed that all `StreamController`s hold onto resources and can cause memory leaks,.

**Comment by matanlurey** [comment]
+1

**Comment by kwalrath** [comment]
@devoncarew / @filiph / @kevmoo do you object to removing close_sinks from the web-angular template? What about other templates and analysis_options files?

**Comment by kevmoo** [comment]
All the same – yes please

**Comment by chalin** [comment]
> we'll need this change in our angular examples, too.

Done via https://github.com/dart-lang/site-webdev/pull/978
